export enum WsMessage {
    // system
    PING = "PING",
    PONG = "PONG",
    ERROR = "ERROR",
  
    // matchmaking

    LEAVE_QUEUE = "LEAVE_QUEUE",

    JOIN_QUEUE = "JOIN_QUEUE",
    MATCH_FOUND = "MATCH_FOUND",
  
    PEER_RECONNECTING = "PEER_RECONNECTING",
    PEER_RECONNECTED = "PEER_RECONNECTED",
  
    END_CONVERSATION = "END_CONVERSATION",
    FIND_ANOTHER_MATCH = "FIND_ANOTHER_MATCH",
    RESUME_CONVERSATION = "RESUME_CONVERSATION",
    REQUEST_RESUME  = "REQUEST_RESUME",
    INVALID_CONVERSATION_ID = "INVALID_CONVERSATION_ID",
  
    // chat
    CHAT_MESSAGE = "CHAT_MESSAGE",
    PEER_DISCONNECTED = "PEER_DISCONNECTED",
    TYPING_START = "TYPING_START",
    TYPING_STOP = "TYPING_STOP",
    END_CHAT = "END_CHAT"
  }
  